package com.axonactive.training.address;

import java.util.Date;


import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.axonactive.training.gpslocation.GpsLocation;

@Entity
@NoArgsConstructor 
@Table(name ="tbl_Address")
public @Getter @Setter class Address {
	/**
	 * an identifier string to recognize an Address. it will be automatically generated by the system.
	 */

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	
	@Column(name = "country", length = 50, nullable = false)
	private String country;
	
	@Column(name = "province", length = 50, nullable = false)
	private String province;
	
	@Column(name = "district", length = 50, nullable = false)
	private String district;
	
	@Column(name = "ward", length = 50)
	private String ward;
	
	@Column(name = "street", length = 50, nullable = false)
	private String street;
	
	@Column(name = "houseNr", length = 50)
	private String houseNr;
	
	@Column(name = "validFrom")
	@Temporal(TemporalType.DATE)
	private Date validFrom;
	
	@Column(name = "validTo")
	@Temporal(TemporalType.DATE)
	private Date validTo;
	
	@OneToOne (cascade = CascadeType.ALL)
//	@OneToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name="fk_gpslocation")
	private GpsLocation gpsLocation;
	
	/**
	 * @param country
	 * @param province
	 * @param district
	 * @param ward
	 * @param street
	 * @param houseNr
	 * @param validFrom
	 * @param validTo
	 * @param gpsLocation
	 */
	public Address(String country, String province, String district, String ward, String street, String houseNr,
			Date validFrom, Date validTo, com.axonactive.training.gpslocation.GpsLocation gpsLocation) {
		this.country = country;
		this.province = province;
		this.district = district;
		this.ward = ward;
		this.street = street;
		this.houseNr = houseNr;
		this.validFrom = validFrom;
		this.validTo = validTo;

		this.gpsLocation = gpsLocation;
	}


	public Address(String country, String province, String district, String street) {
		this.country = country;
		this.province = province;
		this.district = district;
		this.street = street;
	} 
	
	
}
